dag_id: "my_etl_pipeline"
start_date: "2025-01-01"
schedule_interval: "@daily"

tasks:
  - id: "extract"
    bash_command: "echo '[Extract] Simulating data extraction...'"
  - id: "transform"
    bash_command: "echo '[Transform] Simulating data transformation...'"
  - id: "load"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_customers_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "customers"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_customers_dataset.csv"