dag_id: "correlion_olist"
start_date: "2025-01-01"
schedule_interval: "@daily"

tasks:
  - id: "load_customers"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_customers_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "customers"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_customers_dataset.csv"
  - id: "load_geolocation"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_geolocation_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "geolocation"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_geolocation_dataset.csv"
  - id: "load_order_items"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_order_items_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "order_items"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_order_items_dataset.csv"
  - id: "load_order_payments"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_order_payments_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "order_payments"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_order_payments_dataset.csv"
  - id: "load_order_reviews"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_order_reviews_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "order_reviews"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_order_reviews_dataset.csv"
  - id: "load_orders"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_orders_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "orders"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_orders_dataset.csv"
  - id: "load_products"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_products_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "products"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_products_dataset.csv"
  - id: "load_sellers"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_sellers_dataset.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "sellers"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_sellers_dataset.csv"
  - id: "load_product_category_name_translation"
    gcs_bucket: "correlion_olist"
    gcs_object_name: "olist_product_category_name_translation.csv"
    bq_project: "correlion"
    bq_dataset: "olist_staging"
    bq_table: "product_category_name_translation"
    csv_file_path: "/Users/d.lucker/Code/correlion/airflow_demo/source_data/olist_product_category_name_translation.csv"